const sampleData = {
  products: [
    {
      name: 'Classic Cotton T-Shirt',
      slug: 'classic-cotton-tshirt',
      category: 'Shirts',
      images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
      price: '29.99',
      brand: 'Urban Comfort',
      rating: 4.5,
      numReviews: 128,
      stock: 45,
      description: 'Soft and breathable cotton t-shirt perfect for everyday wear. Available in multiple colors.',
      isFeatured: true,
      banner: '/images/banner-1.jpg',
    },
    {
      name: 'Slim Fit Denim Jeans',
      slug: 'slim-fit-denim-jeans',
      category: 'Pants',
      images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
      price: '79.99',
      brand: 'DenimCo',
      rating: 4.8,
      numReviews: 256,
      stock: 23,
      description: 'Premium quality slim fit jeans with stretch fabric for comfort and style.',
      isFeatured: true,
      banner: '/images/banner-2.jpg',
    },
    {
      name: 'Casual Hoodie',
      slug: 'casual-hoodie',
      category: 'Hoodies',
      images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
      price: '49.99',
      brand: 'CozyWear',
      rating: 4.3,
      numReviews: 89,
      stock: 150,
      description: 'Warm and comfortable hoodie with adjustable drawstring and front pocket.',
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Leather Jacket',
      slug: 'leather-jacket',
      category: 'Jackets',
      images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
      price: '199.99',
      brand: 'StyleCraft',
      rating: 4.7,
      numReviews: 342,
      stock: 67,
      description: 'Genuine leather jacket with classic design and durable construction.',
      isFeatured: true,
      banner: '/images/banner-1.jpg',
    },
    {
      name: 'Summer Dress',
      slug: 'summer-dress',
      category: 'Dresses',
      images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
      price: '69.99',
      brand: 'Elegance',
      rating: 4.4,
      numReviews: 167,
      stock: 0,
      description: 'Lightweight and flowy summer dress perfect for warm weather occasions.',
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Athletic Shorts',
      slug: 'athletic-shorts',
      category: 'Shorts',
      images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
      price: '34.99',
      brand: 'FitActive',
      rating: 4.2,
      numReviews: 94,
      stock: 200,
      description: 'Moisture-wicking athletic shorts with elastic waistband for maximum comfort.',
      isFeatured: false,
      banner: null,
    },
  ],
}

export default sampleData
